import type { NextPage } from 'next'
import Head from 'next/head'
import CssBaseline from '@mui/material/CssBaseline';

import { Accordion, AccordionDetails, AccordionSummary, AppBar, Container, Stack, Toolbar, Typography, Card, CardActions, CardContent, Button, Input} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import sqlresults from './eac-equity.test.js';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CssBaseline />
        <AppBar position='static'>
          <Toolbar>
            <Typography component='div' sx={{fixedGrow: 1}}>Reports &gt; EAC Equity Report</Typography>
          </Toolbar>
        </AppBar>

        <Container>
          <Accordion>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              id="report-title"
            >
              <Typography>Report Overview: EAC Equity Subgroups</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                Lorem ipsum
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Card variant='outlined' sx={{p: 1}}>
            <Typography variant='h6' component='div'>Report Options</Typography>
            {/* <Stack> */}
              <label>
                EAC Export Spreadsheet (.XLS format)
                <Input type="file" inputProps={{ accept: ".xlsx" }} sx={{m: 1}} onChange={function(e) {
                  window.alert("1");
                }} />
                {/* <Button variant="contained" component="span">Upload</Button> */}
              </label>
              <Button variant="contained">
                Generate Report
                </Button>
            {/* </Stack> */}
          </Card>
        </Container>

        <Container  id="report-generated" sx={{p: 1}}>
          <Typography variant='h6' component='div'>EAC Equity Report</Typography>
        </Container>
        <Container  id="report-loading" sx={{p: 1}}>
          <Typography component='div'>Fill out the report options above to begin.</Typography>
        </Container>
      </main>

      {/* <footer>
        <Container>
          <Card variant='outlined' sx={{p: 1}}>
            <Typography sx={{ fontStyle: 'italic' }} component='div'>
              Report bugs or suggestions to <a href="mailto:Westley.Trevino@sjcd.edu">Westley.Trevino@sjcd.edu</a>.
            </Typography>
          </Card>
        </Container>
      </footer> */}
    </>
  )
}

export default Home
